### ISSUE TITLE
Remove auto generated comments.

### ISSUE THREAD

**Issue by matteoboehringer** [aetherpowered/aron-java#2]
There are some comments that should be removed

https://github.com/aetherpowered/aron-java/blob/14b3147cf3d5c4db9641fc560e29be6ac005fdb1/settings.gradle#L1-L8

**Comment by shadowcoree** [comment]
You're right. Ima go ahead and remove the comments.

**Comment by shadowcoree** [comment]
Has been fixed with latest commit 33475a8f1068df428f39a9aa18df0279a21e96ff
Thank you for your report. Much obliged.

**Comment by matteoboehringer** [comment]
Thank you nice man. You seem very competent and fast!
